import { escapeHtml, confluenceMacro, getCommitSha, nowISO } from "./utils.js";
import type { RouteInfo } from "./extractRoutes.js";
import type { PermissionsMatrix } from "./extractPermissions.js";
import type { FlowDiagram } from "./extractFlows.js";
import type { UseCase } from "./extractUseCases.js";

/* ── Types ────────────────────────────────────────────────────── */

export interface ConfluencePage {
  title: string;
  /** If set, this page will be created as a child of the page with this title. */
  parentTitle?: string;
  /** Confluence storage format HTML body. */
  body: string;
}

/* ── Reusable HTML fragments ─────────────────────────────────── */

function footer(): string {
  return `<hr/><p><em>Auto-generated by LeaseBase docs-engine · Commit: <code>${escapeHtml(getCommitSha())}</code> · ${escapeHtml(nowISO())}</em></p>`;
}

function h1(text: string): string {
  return `<h1>${escapeHtml(text)}</h1>`;
}
function h2(text: string): string {
  return `<h2>${escapeHtml(text)}</h2>`;
}
function h3(text: string): string {
  return `<h3>${escapeHtml(text)}</h3>`;
}

function ul(items: string[]): string {
  if (items.length === 0) return "<p><em>None</em></p>";
  return "<ul>" + items.map((i) => `<li>${escapeHtml(i)}</li>`).join("") + "</ul>";
}

function ol(items: string[]): string {
  if (items.length === 0) return "<p><em>None</em></p>";
  return "<ol>" + items.map((i) => `<li>${escapeHtml(i)}</li>`).join("") + "</ol>";
}

function table(headers: string[], rows: string[][]): string {
  const thead = "<thead><tr>" + headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("") + "</tr></thead>";
  const tbody =
    "<tbody>" +
    rows.map((row) => "<tr>" + row.map((cell) => `<td>${cell}</td>`).join("") + "</tr>").join("") +
    "</tbody>";
  return `<table>${thead}${tbody}</table>`;
}

function mermaidBlock(code: string): string {
  return confluenceMacro("code", code, { language: "text", title: "Mermaid Diagram" });
}

function infoPanel(body: string): string {
  return `<ac:structured-macro ac:name="info" ac:schema-version="1"><ac:rich-text-body>${body}</ac:rich-text-body></ac:structured-macro>`;
}

/* ── Page generators ─────────────────────────────────────────── */

function generateRootPage(): ConfluencePage {
  return {
    title: "LeaseBase Web Documentation",
    body: [
      h1("LeaseBase Web Documentation"),
      "<p>Automatically generated documentation for the LeaseBase web client application.</p>",
      "<p>This documentation is synchronized with the codebase and updated on every merge to <code>main</code>.</p>",
      h2("Contents"),
      "<ul>",
      '<li><ac:link><ri:page ri:content-title="Overview" /></ac:link></li>',
      '<li><ac:link><ri:page ri:content-title="User Flows" /></ac:link></li>',
      '<li><ac:link><ri:page ri:content-title="Use Cases" /></ac:link></li>',
      '<li><ac:link><ri:page ri:content-title="Page Reference" /></ac:link></li>',
      '<li><ac:link><ri:page ri:content-title="Permissions Matrix" /></ac:link></li>',
      '<li><ac:link><ri:page ri:content-title="Error Handling" /></ac:link></li>',
      '<li><ac:link><ri:page ri:content-title="Testing Scenarios" /></ac:link></li>',
      "</ul>",
      footer(),
    ].join("\n"),
  };
}

function generateOverviewPage(
  routes: RouteInfo[],
  permissions: PermissionsMatrix,
): ConfluencePage {
  const activeRoutes = routes.filter((r) => !r.isRedirect);
  const personas = permissions.personas.filter((p) => p !== "public");

  return {
    title: "Overview",
    parentTitle: "LeaseBase Web Documentation",
    body: [
      h1("Overview"),
      h2("System Architecture"),
      "<p>LeaseBase Web is a <strong>Next.js</strong> (TypeScript) application using the <strong>App Router</strong> with <strong>Tailwind CSS</strong>.</p>",
      ul([
        "Frontend framework: Next.js 14 (App Router)",
        "Styling: Tailwind CSS 3.x",
        "State management: Zustand",
        "Authentication: AWS Cognito (+ dev bypass mode)",
        "API communication: Fetch-based client with auth token injection",
        "Deployment: Docker / AWS ECS",
      ]),
      h2("Personas"),
      "<p>The application supports the following user personas:</p>",
      table(
        ["Persona", "Backend Roles", "Description"],
        [
          ["Property Manager", "ORG_ADMIN, PM_STAFF", "Manages properties for multiple owners and landlords"],
          ["Property Owner", "OWNER", "Owns and rents out properties"],
          ["Tenant", "TENANT", "Rents a property and manages their lease"],
          ["Agent", "(Future)", "Handles showings — not yet active"],
          ["Vendor", "(Future)", "Maintenance vendor — not yet active"],
        ],
      ),
      h2("Authentication"),
      "<p>Authentication supports two modes:</p>",
      ul([
        "Cognito mode: email/password login via AWS Cognito, token stored in Zustand + localStorage",
        "Dev bypass mode: local development only, allows selecting a role without Cognito",
      ]),
      "<p>Auth state is managed by the Zustand auth store (<code>src/lib/auth/store.ts</code>). " +
        "Protected routes use the <code>useRequireAuth</code> hook which redirects unauthenticated users to <code>/auth/login</code>.</p>",
      h2("Routes Summary"),
      `<p>Total routes: <strong>${routes.length}</strong> (${activeRoutes.length} active, ${routes.length - activeRoutes.length} redirects)</p>`,
      footer(),
    ].join("\n"),
  };
}

function generateUserFlowsPage(flows: FlowDiagram[]): ConfluencePage {
  const sections = flows.map((flow) =>
    [
      h2(flow.title),
      `<p>${escapeHtml(flow.description)}</p>`,
      mermaidBlock(flow.mermaid),
    ].join("\n"),
  );

  return {
    title: "User Flows",
    parentTitle: "LeaseBase Web Documentation",
    body: [h1("User Flows"), ...sections, footer()].join("\n"),
  };
}

function generateUseCasesPage(useCases: UseCase[]): ConfluencePage {
  // Group by category
  const categories = new Map<string, UseCase[]>();
  for (const uc of useCases) {
    if (!categories.has(uc.category)) categories.set(uc.category, []);
    categories.get(uc.category)!.push(uc);
  }

  const sections: string[] = [];
  for (const [category, cases] of categories) {
    sections.push(h2(category));
    for (const uc of cases) {
      sections.push(
        h3(uc.title),
        table(
          ["Field", "Value"],
          [
            ["Actors", uc.actors.join(", ")],
            ["Entry Point", `<code>${escapeHtml(uc.entryPoint)}</code>`],
            ["Preconditions", ul(uc.preconditions)],
            ["Steps", ol(uc.steps)],
            ["Alternate Flows", ul(uc.alternateFlows)],
            ["Errors", ul(uc.errors)],
            ["Permissions", uc.permissions.join(", ")],
            ["API Dependencies", uc.apiDependencies.length ? uc.apiDependencies.map((a) => `<code>${escapeHtml(a)}</code>`).join(", ") : "<em>None detected</em>"],
          ],
        ),
      );
    }
  }

  return {
    title: "Use Cases",
    parentTitle: "LeaseBase Web Documentation",
    body: [h1("Use Cases"), ...sections, footer()].join("\n"),
  };
}

function generatePageReferencePage(routes: RouteInfo[], permissions: PermissionsMatrix): ConfluencePage {
  const activeRoutes = routes.filter((r) => !r.isRedirect);

  const sections = activeRoutes.map((route) => {
    const permEntry = permissions.entries.find((e) => e.route === route.route);
    const personas = permEntry?.personas || [];

    return [
      h3(permEntry?.label || route.route),
      table(
        ["Field", "Value"],
        [
          ["Route", `<code>${escapeHtml(route.route)}</code>`],
          ["File", `<code>${escapeHtml(route.filePath)}</code>`],
          ["Purpose", route.requiresAuth ? "Authenticated app page" : "Public page"],
          ["Components", route.components.length ? route.components.map((c) => `<code>${escapeHtml(c)}</code>`).join(", ") : "<em>None imported</em>"],
          ["Actions / Navigation", route.navigationTargets.length ? route.navigationTargets.map((t) => `<code>${escapeHtml(t)}</code>`).join(", ") : "<em>None</em>"],
          ["API Dependencies", route.apiCalls.length ? route.apiCalls.map((a) => `<code>${escapeHtml(a)}</code>`).join(", ") : "<em>None</em>"],
          ["Personas", personas.length ? personas.join(", ") : "<em>All</em>"],
        ],
      ),
    ].join("\n");
  });

  return {
    title: "Page Reference",
    parentTitle: "LeaseBase Web Documentation",
    body: [h1("Page Reference"), ...sections, footer()].join("\n"),
  };
}

function generatePermissionsMatrixPage(permissions: PermissionsMatrix): ConfluencePage {
  const personas = permissions.personas;
  const headers = ["Route", "Label", ...personas];
  const rows = permissions.entries.map((entry) => [
    `<code>${escapeHtml(entry.route)}</code>`,
    escapeHtml(entry.label) + (entry.isFuture ? " <em>(future)</em>" : ""),
    ...personas.map((p) => (entry.personas.includes(p) ? "✅" : "—")),
  ]);

  return {
    title: "Permissions Matrix",
    parentTitle: "LeaseBase Web Documentation",
    body: [
      h1("Permissions Matrix"),
      "<p>Matrix showing which personas can access each route.</p>",
      table(headers, rows),
      footer(),
    ].join("\n"),
  };
}

function generateErrorHandlingPage(): ConfluencePage {
  return {
    title: "Error Handling",
    parentTitle: "LeaseBase Web Documentation",
    body: [
      h1("Error Handling"),
      h2("Authentication Errors"),
      ul([
        "401 Unauthorized → auto-logout via auth store, redirect to /auth/login",
        "403 Forbidden → auto-logout via auth store, redirect to /auth/login",
        "Session expired (token expiry) → redirect to /auth/login on next page load",
      ]),
      h2("API Errors"),
      ul([
        "Non-2xx responses → error message extracted from response body JSON",
        "Network errors → generic error message displayed",
        "Non-JSON responses → raw text surfaced to caller",
        "Empty responses → treated as undefined",
      ]),
      h2("Client-Side Validation"),
      ul([
        "Registration: password length ≥ 8 characters, passwords must match",
        "Email verification: 6-digit code required",
        "Login: email and password required fields",
      ]),
      h2("Error Display"),
      ul([
        "Form errors: red text below form fields",
        "Toast notifications: via ToastProvider in app shell",
        "Loading states: disabled buttons with loading text, skeleton placeholders",
      ]),
      footer(),
    ].join("\n"),
  };
}

function generateTestingScenariosPage(routes: RouteInfo[], useCases: UseCase[]): ConfluencePage {
  const scenarios: string[] = [];

  // Auth scenarios
  scenarios.push(h2("Authentication Tests"));
  scenarios.push(
    table(
      ["Scenario", "Steps", "Expected Result"],
      [
        ["Login with valid credentials", "Enter valid email/password, click Sign In", "Redirect to /app dashboard"],
        ["Login with invalid credentials", "Enter wrong password, click Sign In", "Error message shown"],
        ["Login with unverified email", "Enter unverified user, click Sign In", "Prompted to verify email"],
        ["Register new user", "Fill all fields correctly, submit", "Redirect to email verification"],
        ["Register with mismatched passwords", "Enter different passwords", "Client-side error shown"],
        ["Verify email with valid code", "Enter correct 6-digit code", "Redirect to login with success"],
        ["Resend verification code", "Click Resend Code", "Success message shown"],
        ["Dev bypass login", "Select role, click dev bypass", "Redirect to /app (dev only)"],
      ],
    ),
  );

  // Navigation scenarios
  scenarios.push(h2("Navigation Tests"));
  scenarios.push(
    table(
      ["Scenario", "Steps", "Expected Result"],
      [
        ["Unauthenticated access to /app", "Navigate to /app without login", "Redirect to /auth/login"],
        ["Dashboard persona routing", "Login as PM, Owner, or Tenant", "Correct dashboard variant shown"],
        ["Sidebar navigation", "Click each nav item", "Correct page loads, active state shown"],
        ["Mobile menu toggle", "Open/close hamburger menu", "Menu opens/closes with animation"],
        ["Breadcrumb navigation", "Navigate to nested page", "Breadcrumbs show correct path"],
      ],
    ),
  );

  // Per-use-case scenarios
  scenarios.push(h2("Use Case Scenarios"));
  const ucRows = useCases.map((uc) => [
    escapeHtml(uc.title),
    uc.steps[0] || "",
    "Page loads successfully with correct content",
  ]);
  scenarios.push(table(["Use Case", "Entry Step", "Expected"], ucRows));

  return {
    title: "Testing Scenarios",
    parentTitle: "LeaseBase Web Documentation",
    body: [h1("Testing Scenarios"), ...scenarios, footer()].join("\n"),
  };
}

/* ── Public API ───────────────────────────────────────────────── */

export function generateConfluencePages(
  routes: RouteInfo[],
  permissions: PermissionsMatrix,
  flows: FlowDiagram[],
  useCases: UseCase[],
): ConfluencePage[] {
  return [
    generateRootPage(),
    generateOverviewPage(routes, permissions),
    generateUserFlowsPage(flows),
    generateUseCasesPage(useCases),
    generatePageReferencePage(routes, permissions),
    generatePermissionsMatrixPage(permissions),
    generateErrorHandlingPage(),
    generateTestingScenariosPage(routes, useCases),
  ];
}
